[pytest]
pythonpath = src
testpaths = tests/unit tests/integration
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
filterwarnings =
    error
addopts = --strict-markers -v --cov=src --cov-config=.coveragerc
norecursedirs = .* old *.egg .eggs dist build .tox .git __pycache__
markers =
    integration: marks tests as integration tests
    performance: marks tests as performance benchmarks
    slow: marks tests as slow running tests
    benchmark: marks tests as benchmark tests
    e2e: marks tests as end-to-end tests
