name: 'Setup Rust with Caching'
description: 'Install Rust with specified toolchain and setup cargo caching'
inputs:
  toolchain:
    description: 'Rust toolchain version'
    required: false
    default: 'stable'
  components:
    description: 'Additional components to install (comma-separated)'
    required: false
    default: ''
  targets:
    description: 'Additional targets to install (comma-separated)'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Suffix for cache key'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
