from __future__ import annotations
from antidote import inject
from rich.console import Console
from pydantic import Field
from ..console import get_console
from ..thunk import Thunk
from .base import SchemaBase

class FinalAnswerSchema(SchemaBase):
  """Schema for the final answer generated by the Goldentooth Agent."""
  final_answer: str = Field(..., description="The final answer generated by the Goldentooth Agent.")

  @inject
  def print(self, console: Console = inject[get_console()]) -> None:
    """Print the schema in a pretty format using rich."""
    console.print(self.final_answer)

  @classmethod
  def from_final_answer(cls, final_answer: str) -> FinalAnswerSchema:
    """Create a FinalAnswerSchema instance from a final answer."""
    return cls(final_answer=final_answer)

def wrap_final_answer_th() -> Thunk[str, FinalAnswerSchema]:
  async def _thunk(user_input: str) -> FinalAnswerSchema:
    """Wrap user input in an FinalAnswerSchema instance."""
    return FinalAnswerSchema.from_final_answer(user_input)
  return Thunk(_thunk)
