from __future__ import annotations
from antidote import inject
from rich.console import Console
from pydantic import Field
from ..console import get_console
from ..thunk import Thunk
from .base import SchemaBase

class GreetingSchema(SchemaBase):
  """Schema for the greeting generated by the Goldentooth Agent."""
  greeting: str = Field(..., description="The greeting generated by or on behalf of the Goldentooth Agent.")

  @inject
  def print(self, console: Console = inject[get_console()]) -> None:
    """Print the schema in a pretty format using rich."""
    console.print(self.greeting)

  @classmethod
  def from_greeting(cls, greeting: str) -> GreetingSchema:
    """Create a GreetingSchema instance from a greeting."""
    return cls(greeting=greeting)

def wrap_greeting_th() -> Thunk[str, GreetingSchema]:
  async def _thunk(user_input: str) -> GreetingSchema:
    """Wrap user input in an GreetingSchema instance."""
    return GreetingSchema.from_greeting(user_input)
  return Thunk(_thunk)
