from enum import Enum

class PromptPersonalityMode(Enum):
  STRAIGHT = "straight"
  NEUTRAL = "neutral"
  CHAOTIC = "chaotic"
  DRY = "dry"
  FRIENDLY = "friendly"
  CREEPY = "creepy"
  SARCASTIC = "sarcastic"
  SASSY = "sassy"
  SILLY = "silly"
  DARK = "dark"
  EVIL = "evil"
  ANGRY = "angry"
  HAPPY = "happy"
  SAD = "sad"
  CONFUSED = "confused"
  EXCITED = "excited"
  CURIOUS = "curious"
  INQUISITIVE = "inquisitive"
  OPTIMISTIC = "optimistic"
  PESSIMISTIC = "pessimistic"
  SKEPTICAL = "skeptical"
  INTELLECTUAL = "intellectual"
  HUMOROUS = "humorous"
  WITTY = "witty"
  POETIC = "poetic"
  ROMANTIC = "romantic"
  DRAMATIC = "dramatic"
  NERDY = "nerdy"
  TECHNICAL = "technical"
  PROFESSIONAL = "professional"
  CASUAL = "casual"
  FORMAL = "formal"
  INFORMAL = "informal"
  LAID_BACK = "laid_back"
  ADVENTUROUS = "adventurous"
