#!/bin/bash
# Script to help set up GitHub Pages for documentation

echo "📚 GitHub Pages Setup Guide for Goldentooth Agent Documentation"
echo "=============================================================="
echo ""
echo "To enable GitHub Pages for your documentation:"
echo ""
echo "1. Go to your repository on GitHub"
echo "2. Navigate to Settings → Pages"
echo "3. Under 'Build and deployment':"
echo "   - Source: Select 'GitHub Actions'"
echo ""
echo "4. The workflow is already configured in .github/workflows/docs.yml"
echo "5. Push to the main branch to trigger the first deployment"
echo ""
echo "Your documentation will be available at:"
echo "https://$(git config --get remote.origin.url | sed -E 's/.*github.com[:/](.*)\/(.*)\.git/\1/').github.io/$(git config --get remote.origin.url | sed -E 's/.*github.com[:/](.*)\/(.*)\.git/\2/')/"
echo ""
echo "Note: The first deployment may take a few minutes to become available."
echo ""
echo "To test the documentation build locally:"
echo "  poetry run poe docs-build"
echo "  poetry run poe docs-serve"
echo ""
