name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.88.0
        components: clippy, rustfmt

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-test-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Goldentooth MCP Server
      run: |
        # Create target directory for test binaries
        mkdir -p target/test-binaries
        # Download the appropriate binary for Linux x86_64
        curl -L -o target/test-binaries/goldentooth-mcp \
          https://github.com/goldentooth/mcp-server/releases/latest/download/goldentooth-mcp-x86_64-linux
        # Make it executable
        chmod +x target/test-binaries/goldentooth-mcp
        # Verify it works and set environment variables to suppress all logs
        echo "RUST_LOG=off" >> $GITHUB_ENV
        echo "LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "GOLDENTOOTH_LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "MCP_LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "SILENT=1" >> $GITHUB_ENV
        echo "QUIET=1" >> $GITHUB_ENV
        ./target/test-binaries/goldentooth-mcp --version 2>/dev/null || echo "MCP server installed successfully"

    - name: Check formatting
      run: cargo fmt --all -- --check

    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Run tests
      run: cargo test --verbose --all-features

    - name: Run integration tests
      run: cargo test --test '*' --verbose

    - name: Check that project builds
      run: cargo build --verbose --all-features

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install cargo-audit
      run: cargo install cargo-audit

    - name: Run security audit
      run: cargo audit

  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: llvm-tools-preview

    - name: Install cargo-llvm-cov
      run: cargo install cargo-llvm-cov

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Goldentooth MCP Server
      run: |
        # Create target directory for test binaries
        mkdir -p target/test-binaries
        # Download the appropriate binary for Linux x86_64
        curl -L -o target/test-binaries/goldentooth-mcp \
          https://github.com/goldentooth/mcp-server/releases/latest/download/goldentooth-mcp-x86_64-linux
        # Make it executable
        chmod +x target/test-binaries/goldentooth-mcp
        # Verify it works and set environment variables to suppress all logs
        echo "RUST_LOG=off" >> $GITHUB_ENV
        echo "LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "GOLDENTOOTH_LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "MCP_LOG_LEVEL=OFF" >> $GITHUB_ENV
        echo "SILENT=1" >> $GITHUB_ENV
        echo "QUIET=1" >> $GITHUB_ENV
        ./target/test-binaries/goldentooth-mcp --version 2>/dev/null || echo "MCP server installed successfully"

    - name: Generate coverage report
      run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info

  docs:
    name: Documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Check documentation
      run: cargo doc --no-deps --document-private-items --all-features
      env:
        RUSTDOCFLAGS: "-D warnings"

  build-targets:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation dependencies (Linux aarch64)
      if: matrix.target == 'aarch64-unknown-linux-gnu'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-${{ matrix.target }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

    - name: Build for target
      run: |
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc
        fi
        cargo build --release --target ${{ matrix.target }}
